language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install --no-optional
before_script:
- npm link .
script:
- ./ci/tmplify.js
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/commit_push.js
- ./ci/travis/publish.js

env:
  secure: "i6Y7z//UIJD61X1SF3e1vmD0jUJ5fF1PikKuibYV0MLw2B0gHea0Px0I2czV6Nm5GujwnGtDiS3iOW7/IuYHv3Ip0pQSxHchvypMoHJ9qkgvyDSliDkcjTUYd3x1g2cywNq9mEfRqQSf9JRVPj49MrMTM+gJ5Air/aR9pgAaHOaWIja7eK70rY/7J8h02sW5L/Cp5HTkXjZl2APgYsN2atIEw1LgKfppo1fNDQ54Oo1UmK1mzAYvmLNVvUW04xe7iLFOs/Fh6EP9gVt5u3m9hlzo5XQi37qooiWpAODTY8K0ZbxOBtPjZf5fD/bbwgdkm8/Uxlqo3Xh7umAP+ip5zubWliO2XHaqJbokF1VQQcUFz5Y5z1x8j1RxIoq4ZBBdr0I1KV4RKK0GIbq8iKMhNGvG1PD+gDo5p0JiIm3fkOZv35KG/4U2PApzwx1b9/IFheJqVtyS4jF9Y5PeO/o9kvzT9nfnfBzb8FvfAH+ibMLr4yp8mUvIjuDmbAKkEk8NWfp/Dm19RPQadZUnVzUC+sVtBoVPFTEQYfnUe1BOsK7vegg3APQ2EfoDZguYjTunp3cAtBVeRaZuTqlygisO6Mk72kqqgEC3EwL+yCkTJFgyQTEXt3wjVwdgV/hz/sziryDEBo1e8+RQoNM4S0ZZf0a4xU+nCazGGiB1HswsjDM="
