language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install --no-optional
before_script:
- npm link .
script:
- ./ci/tmplify.js
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/commit_push.js
- ./ci/travis/publish.js
env:
  secure: "VCUloIhVEu9TQK6ca2VL18weIc8ux84AxmSgjnfU5hePPzY45c3Qlny/mj0EK8enf0Adk6oMf7qKjq+oJoIEdzshbRRHg10qF/t5J7Nsse2xNm9CL8nud7B623s4srHN+ckT8DrvLNeJS9n+G1jgcbEygpEcfdRahiFWzbZMH8D/7Y0Mdz7UCg56Twz71JEbFpokCcSAT2yYbw3AIa9UrA43hnGjaXxmcX66zJ4hNj6jn72yVJgxqFz2BtIY6RRV+upjtCtfh52bAgsbdjgWPrl/nUnd8mGn2h7MT1ZMSPsnOHLD5Vj+ZdgyKbSUHCmewbwosA1ZGjechq90ORAfH4MFx4ufzr6l//lNbspo2fUILn6ZsHfwSBp3WKW/choJB8J98/UNDVg3K8m/VkA8tu+fQqmRT6sQEzAIhL/N396dy6buWQMpe75p7z7+hbeNTKAD9fJewkqjS7f30DLU5RpssyXt0O/zyraNZA+fWiguj+SkAcZRC3mkMqCbCZTsW3aYoXAX5FtNOW0pQMRHcjYXC2/F2Qc+1owPfioHZ5glT5Cc7Jg2CSs4NafcLkVs7KCfQjtH9ojalIbmjXJJ2DYaJVqGESuBzi7oY8FDl+AGc7TyLFfNT75cviWOXu9KsjmH857PcPvlQIgRDIELcczKtleXyz+lktB94/5LwkQ="
